[2023-02-18T18:29:06.702-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.5_user_processing.select_data scheduled__2023-02-18T00:00:00+00:00 [queued]>
[2023-02-18T18:29:06.718-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.5_user_processing.select_data scheduled__2023-02-18T00:00:00+00:00 [queued]>
[2023-02-18T18:29:06.720-0600] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T18:29:06.721-0600] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-02-18T18:29:06.722-0600] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T18:29:06.735-0600] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): select_data> on 2023-02-18 00:00:00+00:00
[2023-02-18T18:29:06.738-0600] {standard_task_runner.py:54} INFO - Started process 195944 to run task
[2023-02-18T18:29:06.741-0600] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '1.5_user_processing', 'select_data', 'scheduled__2023-02-18T00:00:00+00:00', '--job-id', '509', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.5_user_processing.py', '--cfg-path', '/tmp/tmpx50coj29']
[2023-02-18T18:29:06.743-0600] {standard_task_runner.py:83} INFO - Job 509: Subtask select_data
[2023-02-18T18:29:06.745-0600] {dagbag.py:525} INFO - Filling up the DagBag from /c/Airflow/dags/Introduction_to_Apache_Airflow/1.5_user_processing.py
[2023-02-18T18:29:07.152-0600] {task_command.py:384} INFO - Running <TaskInstance: 1.5_user_processing.select_data scheduled__2023-02-18T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-18T18:29:07.207-0600] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.5_user_processing
AIRFLOW_CTX_TASK_ID=select_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-18T00:00:00+00:00
[2023-02-18T18:29:07.209-0600] {sql.py:254} INFO - Executing: 
                                        SELECT * FROM users
                                    
[2023-02-18T18:29:07.222-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-18T18:29:07.420-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-18T18:29:07.426-0600] {sql.py:375} INFO - Running statement: 
                                        SELECT * FROM users
                                    , parameters: None
[2023-02-18T18:29:07.427-0600] {sql.py:384} INFO - Rows affected: 15
[2023-02-18T18:29:07.447-0600] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=1.5_user_processing, task_id=select_data, execution_date=20230218T000000, start_date=20230219T002906, end_date=20230219T002907
[2023-02-18T18:29:07.475-0600] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-02-18T18:29:07.499-0600] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
