[2023-02-20T09:18:38.920-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.6.1_user_processing.store_user scheduled__2023-02-19T00:00:00+00:00 [queued]>
[2023-02-20T09:18:38.932-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.6.1_user_processing.store_user scheduled__2023-02-19T00:00:00+00:00 [queued]>
[2023-02-20T09:18:38.933-0600] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T09:18:38.934-0600] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-02-20T09:18:38.935-0600] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-20T09:18:38.946-0600] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-02-19 00:00:00+00:00
[2023-02-20T09:18:38.949-0600] {standard_task_runner.py:54} INFO - Started process 198709 to run task
[2023-02-20T09:18:38.952-0600] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '1.6.1_user_processing', 'store_user', 'scheduled__2023-02-19T00:00:00+00:00', '--job-id', '571', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.6.1_user_processing.py', '--cfg-path', '/tmp/tmpoqqj1mve']
[2023-02-20T09:18:38.954-0600] {standard_task_runner.py:83} INFO - Job 571: Subtask store_user
[2023-02-20T09:18:38.955-0600] {dagbag.py:525} INFO - Filling up the DagBag from /c/Airflow/dags/Introduction_to_Apache_Airflow/1.6.1_user_processing.py
[2023-02-20T09:18:39.326-0600] {task_command.py:384} INFO - Running <TaskInstance: 1.6.1_user_processing.store_user scheduled__2023-02-19T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-20T09:18:39.391-0600] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.6.1_user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-02-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-19T00:00:00+00:00
[2023-02-20T09:18:39.393-0600] {postgres.py:158} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /c/Users/tinma/OneDrive/Escritorio/processed_user.csv
[2023-02-20T09:18:39.425-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-20T09:18:39.444-0600] {python.py:177} INFO - Done. Returned value was: None
[2023-02-20T09:18:39.591-0600] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=1.6.1_user_processing, task_id=store_user, execution_date=20230219T000000, start_date=20230220T151838, end_date=20230220T151839
[2023-02-20T09:18:39.648-0600] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-02-20T09:18:39.685-0600] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
