[2023-02-21T08:48:34.499-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.6.2_user_processing.store_user scheduled__2023-02-20T00:00:00+00:00 [queued]>
[2023-02-21T08:48:34.523-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.6.2_user_processing.store_user scheduled__2023-02-20T00:00:00+00:00 [queued]>
[2023-02-21T08:48:34.527-0600] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-21T08:48:34.535-0600] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-02-21T08:48:34.542-0600] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-21T08:48:34.602-0600] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-02-20 00:00:00+00:00
[2023-02-21T08:48:34.610-0600] {standard_task_runner.py:54} INFO - Started process 428378 to run task
[2023-02-21T08:48:34.614-0600] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '1.6.2_user_processing', 'store_user', 'scheduled__2023-02-20T00:00:00+00:00', '--job-id', '618', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.6.2_user_processing.py', '--cfg-path', '/tmp/tmpb4oq6g2z']
[2023-02-21T08:48:34.618-0600] {standard_task_runner.py:83} INFO - Job 618: Subtask store_user
[2023-02-21T08:48:34.624-0600] {dagbag.py:525} INFO - Filling up the DagBag from /c/Airflow/dags/Introduction_to_Apache_Airflow/1.6.2_user_processing.py
[2023-02-21T08:48:35.850-0600] {task_command.py:384} INFO - Running <TaskInstance: 1.6.2_user_processing.store_user scheduled__2023-02-20T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-21T08:48:35.966-0600] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.6.2_user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-20T00:00:00+00:00
[2023-02-21T08:48:35.971-0600] {postgres.py:158} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /c/Users/tinma/OneDrive/Escritorio/processed_user.csv
[2023-02-21T08:48:36.039-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-21T08:48:36.110-0600] {python.py:177} INFO - Done. Returned value was: None
[2023-02-21T08:48:36.357-0600] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=1.6.2_user_processing, task_id=store_user, execution_date=20230220T000000, start_date=20230221T144834, end_date=20230221T144836
[2023-02-21T08:48:36.439-0600] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-02-21T08:48:36.486-0600] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
