[2023-02-16 11:57:42,227] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1.6_user_processing.store_user manual__2023-02-16T17:57:32.619139+00:00 [queued]>
[2023-02-16 11:57:42,234] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1.6_user_processing.store_user manual__2023-02-16T17:57:32.619139+00:00 [queued]>
[2023-02-16 11:57:42,234] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-16 11:57:42,238] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-16 11:57:42,238] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-16 11:57:42,247] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2023-02-16 17:57:32.619139+00:00
[2023-02-16 11:57:42,250] {standard_task_runner.py:52} INFO - Started process 74241 to run task
[2023-02-16 11:57:42,252] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1.6_user_processing', 'store_user', 'manual__2023-02-16T17:57:32.619139+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.6_user_processing.py', '--cfg-path', '/tmp/tmpmuo83_fd', '--error-file', '/tmp/tmps1jh2tey']
[2023-02-16 11:57:42,253] {standard_task_runner.py:80} INFO - Job 250: Subtask store_user
[2023-02-16 11:57:42,301] {task_command.py:369} INFO - Running <TaskInstance: 1.6_user_processing.store_user manual__2023-02-16T17:57:32.619139+00:00 [running]> on host Tinmar.
[2023-02-16 11:57:42,355] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.6_user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-02-16T17:57:32.619139+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-16T17:57:32.619139+00:00
[2023-02-16 11:57:42,357] {postgres.py:158} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /c/Users/tinma/OneDrive/Escritorio/processed_user.csv
[2023-02-16 11:57:42,381] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-02-16 11:57:42,396] {python.py:173} INFO - Done. Returned value was: None
[2023-02-16 11:57:42,409] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1.6_user_processing, task_id=store_user, execution_date=20230216T175732, start_date=20230216T175742, end_date=20230216T175742
[2023-02-16 11:57:42,435] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-16 11:57:42,466] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
